---
- name: content copy
  hosts: all 
  tasks:
    - name: get rest api
      uri:
        validate_certs: no
        url: 'https://vm251-81.gsslab.pnq2.redhat.com/api/v2/config/'
        user: admin
        password: redhat
        body_format: json
        force_basic_auth: yes
        return_content: yes
        method: GET
      register: response_pa_config

    - debug: 
        msg: "{{ response_pa_config.content }}"

 
    - name: Save config
      copy:
        content: '{{ response_pa_config.content }}'
        dest: '/tmp/backup.txt'
        
