---
- name: content copy
  hosts: localhost
  tasks:
    - name: get rest api
      uri:
        validate_certs: no
        url: 'https://vm251-81.gsslab.pnq2.redhat.com/api/v2/config/'
        user: admin
        password: redhat
        body_format: json
        force_basic_auth: yes
        return_content: yes
        method: GET
      register: response_pa_config
    - debug:
        msg: "print Response PA config: {{ response_pa_config.stdout }}"

    - name: Save config
      copy:
        content: '{{ response_pa_config.stdout }}'
        dest: /tmp/backup.txt
        force: yes
    - debug:
        msg:
           - "Saving content to /tmp/paconfig.txt"
